settings:
  debug: false
  silentMenuPermissions: false
  defaultMenu: default
items:
    WATCH: default
menus:
  default:
    title: '&4Your text here'
    rows: 2
    items:
      Stone:
        name: '&6Your text here'
        type: stone
        slot: 5
        actions:
        - command:say Your text here
        - menu:default